image: java:8-jdk

stages:
  - test
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - */build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew check
